name: valvlm
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.2.0=py38h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py38h06a4308_0
  - attrs=24.2.0=py38h06a4308_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py38h06a4308_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli-python=1.0.9=py38h6a678d5_8
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py38h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py38h06a4308_0
  - conda-pack=0.8.0=pyhd8ed1ab_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - debugpy=1.6.7=py38h6a678d5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - exceptiongroup=1.2.0=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - h11=0.14.0=py38h06a4308_0
  - httpcore=1.0.2=py38h06a4308_0
  - httpx=0.27.0=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - ipykernel=6.29.5=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.19.1=py38h06a4308_0
  - jinja2=3.1.4=py38h06a4308_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.23.0=py38h06a4308_0
  - jsonschema-specifications=2023.7.1=py38h06a4308_0
  - jupyter_client=7.4.9=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - jupyter_events=0.10.0=py38h06a4308_0
  - jupyter_server_terminals=0.4.4=py38h06a4308_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py38h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=2.0.4=py38h06a4308_0
  - nb_conda_kernels=2.3.1=py38h06a4308_0
  - nbclassic=1.1.0=py38h06a4308_0
  - nbclient=0.8.0=py38h06a4308_0
  - nbconvert=7.16.4=py38h06a4308_0
  - nbformat=5.10.4=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - openssl=3.4.1=h7b32b05_0
  - overrides=7.4.0=py38h06a4308_0
  - packaging=24.1=py38h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_1
  - platformdirs=3.10.0=py38h06a4308_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-json-logger=2.0.7=py38h06a4308_0
  - pyyaml=6.0.2=py38h5eee18b_0
  - pyzmq=24.0.1=py38h5eee18b_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py38h06a4308_0
  - requests=2.32.3=py38h06a4308_0
  - rfc3339-validator=0.1.4=py38h06a4308_0
  - rfc3986-validator=0.1.1=py38h06a4308_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - send2trash=1.8.2=py38h06a4308_0
  - setuptools=75.1.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py38h06a4308_0
  - soupsieve=2.5=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py38h06a4308_0
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py38h06a4308_0
  - tornado=6.4.1=py38h5eee18b_0
  - traitlets=5.14.3=py38h06a4308_0
  - urllib3=2.2.3=py38h06a4308_0
  - webencodings=0.5.1=py38_1
  - websocket-client=1.8.0=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - annotated-types==0.7.0
      - arrow==1.3.0
      - av==12.3.0
      - blessed==1.20.0
      - cachetools==5.5.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==4.4.2
      - decord==0.6.0
      - distro==1.9.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - ffmpeg==1.4
      - ffmpeg-python==0.2.0
      - filelock==3.16.1
      - flash-attn==2.7.0.post2
      - fonttools==4.54.1
      - fqdn==1.5.1
      - fsspec==2025.2.0
      - ftfy==6.2.3
      - future==1.0.0
      - fuzzywuzzy==0.18.0
      - google-auth==2.37.0
      - google-auth-oauthlib==0.4.6
      - gpustat==1.1.1
      - grpcio==1.68.1
      - h5py==3.11.0
      - hf-transfer==0.1.9
      - huggingface-hub==0.28.1
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-contrib-core==0.4.2
      - jupyter-contrib-nbextensions==0.7.0
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-lsp==2.2.5
      - jupyter-nbextensions-configurator==0.6.4
      - jupyter-server==2.14.2
      - jupyterlab==4.3.7
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lxml==5.3.1
      - markdown==3.7
      - matplotlib==3.7.5
      - modelscope==1.23.0
      - modelspace==0.0.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - networkx==3.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - nvitop==1.3.2
      - oauthlib==3.2.2
      - open-clip-torch==2.30.0
      - openai==1.63.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - pandas==2.0.3
      - pillow==10.4.0
      - proglog==0.1.10
      - protobuf==5.29.1
      - psutil==6.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.4
      - pytz==2024.2
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - safetensors==0.5.2
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentencepiece==0.2.0
      - socksio==1.0.0
      - sympy==1.13.1
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - timm==1.0.14
      - tokenizers==0.19.1
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchinfo==1.8.0
      - torchvision==0.19.1+cu118
      - tqdm==4.66.5
      - transformers==4.40.1
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uri-template==1.3.0
      - visdom==0.2.4
      - visdom-logger==0.1
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
prefix: /home/jhw/miniconda3/envs/gtad1
